
export const ROUTES = [
  '/dashboard/analysis',
  '/dashboard/monitor',
  '/dashboard/workplace',
  '/list/table',
  '/list/basic',
  '/list/card',
  '/form/basic',
  '/form/step',
  '/form/advanced',
  '/profile/basic',
  '/profile/advanced',
  '/result/success',
  '/result/error',
  '/result/success',
  '/result/error',
  '/exception/403',
  '/exception/404',
  '/exception/500',
  '/account/center',
  '/account/setting',
  '/code/theme',
  '/code/template/new',
  '/code/template',
  '/editor/flow',
  '/editor/mind',
];
